apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: asdf-springboot
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/chetna14manku_org/rhtap-qe-springboot:azure-fcc807b27d38ac232abf3d502d0e17dca5f6e97b
        name: container-image  
